### ISSUE TITLE
Strip prefix 2

### ISSUE THREAD

**Issue by steevivo** [faritvidal/Config-Traefik-2.2.X#1]
Hi,
Can you explain the goal of your prefix 2 (middlewares_strip_prefix_2) please ?
thx

**Comment by faritvidal** [comment]
Hello Steevivo

the middlewares_strip_prefix_2 only apply it in this [LINK](https://github.com/faritvidal/Config-Traefik-2.2.X/blob/master/traefik-simple-auth-subpath/traefik_config/configurations/middleware-http.yml) configuration and it is to be able to use all the applications as subpath using the domain instead of using subdomains.

subdomain

- cars.examples.com
- trucks.examples.com
- etc.examples.com

subpath

- examples.com/cars
- examples.com/trucks
- examples.com/etc

The problem that is generated when trying to load the applications that is many require that it ends in **"/"** to be able to enter what this middleware does is to put this **"/"** at the end automatically

1. examples.com/cars/
2. examples.com/trucks/
3. examples.com/etc/

So that the application loads, use it and it worked for me this way after looking for a solution to this problem, I hope I have answered your question
